runtime: python39  # or your preferred Python runtime

env: standard

entrypoint: gunicorn ci.wsgi:application  # Ensure this points to your WSGI application

# Optional: Specify the instance class
instance_class: F2

# Environment Variables
env_variables:
  DJANGO_SECRET_KEY: 'django-insecure-@n3(@^^9292-87i@hv-zlcjq1n)gaez1cl08*6^-i83@ys*8pz'  # Replace with a secure key
  DJANGO_DEBUG: 'False'
  POSTGRES_DB: 'postgres'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: '5ib*J<e}rqFa;Ffd'
  CLOUD_SQL_CONNECTION_NAME: 'focal-charge-439118-q8:us-central1:dro-teste'
  DB_HOST: '/cloudsql/focal-charge-439118-q8:us-central1:dro-teste'  # Added for App Engine

# Specify the Cloud SQL instance to connect to
cloud_sql_instances: 'focal-charge-439118-q8:us-central1:dro-teste'

# Optional: Configure automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
